2022-02-27 00:38:30,480 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 1025615ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 00:53:41,014 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 910531ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 01:10:13,706 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 992684ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 01:27:04,476 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 1010763ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 01:43:08,206 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 963726ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 01:58:51,890 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 943677ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 02:16:24,496 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 1052601ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 02:32:20,106 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 955606ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 02:49:48,818 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 1048708ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 03:07:22,520 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 1053698ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 03:23:42,405 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 979879ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 03:40:43,175 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 1020767ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 03:57:57,885 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 1034706ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 04:12:28,582 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 870688ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 04:27:39,834 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 911241ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 04:44:06,541 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 986698ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 05:00:47,248 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 1000698ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 05:16:08,958 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 921706ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 05:32:33,593 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 984629ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 05:47:42,428 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 908831ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 06:04:58,091 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 1035661ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 06:22:35,460 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 1057363ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 06:39:59,809 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 1044345ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 06:55:30,478 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 930665ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 07:10:54,374 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 923893ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 07:26:32,063 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 937686ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 07:44:08,770 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 1056697ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 08:00:21,567 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 972796ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 08:17:29,494 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 1027920ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 08:35:00,213 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 1050716ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 08:50:10,926 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 910710ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 09:06:21,638 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 970708ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 09:24:14,325 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 1072682ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 09:36:16,361 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 722033ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 09:49:41,602 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 705237ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 09:51:21,748 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 60135ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 10:08:04,026 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 1002268ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 10:25:01,757 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 1017728ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 10:37:10,073 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 728313ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 11:07:19,052 ERROR 54792 nodejs.ClusterClientNoResponseError: client no response in 471087ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 54792
hostname: liuyuledeMacBook-Pro.local

2022-02-27 11:19:40,299 ERROR 54794 [-/127.0.0.1/-/115ms POST /blog/add] nodejs.P2002Error: 
Invalid `prisma.tags.create()` invocation in
/Users/lruler/Desktop/lruler-blog/be/app/controller/blog.ts:27:30

  24 await Promise.all(blogTags.map(async t => {
  25   const o = await prisma.tags.findUnique({ where: { tag: t.tag } });
  26   if (o) await prisma.tags.update({ where: { tag: o.tag }, data: { count: ++o.count } });
→ 27   else await prisma.tags.create(
  Unique constraint failed on the constraint: `Tags_tag_key`
Invalid `prisma.tags.create()` invocation in
/Users/lruler/Desktop/lruler-blog/be/app/controller/blog.ts:27:30

  24 await Promise.all(blogTags.map(async t => {
  25   const o = await prisma.tags.findUnique({ where: { tag: t.tag } });
  26   if (o) await prisma.tags.update({ where: { tag: o.tag }, data: { count: ++o.count } });
→ 27   else await prisma.tags.create(
  Unique constraint failed on the constraint: `Tags_tag_key`
    at Object.request (/Users/lruler/Desktop/lruler-blog/be/node_modules/@prisma/client/runtime/index.js:39809:15)
    at async PrismaClient._request (/Users/lruler/Desktop/lruler-blog/be/node_modules/@prisma/client/runtime/index.js:40637:18)
    at async /Users/lruler/Desktop/lruler-blog/be/app/controller/blog.ts:27:12
    at async Promise.all (index 0)
    at async BlogController.addBlog (/Users/lruler/Desktop/lruler-blog/be/app/controller/blog.ts:24:5)
    at async /Users/lruler/Desktop/lruler-blog/be/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async session (/Users/lruler/Desktop/lruler-blog/be/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/Users/lruler/Desktop/lruler-blog/be/node_modules/koa-bodyparser/index.js:95:5)
    at async /Users/lruler/Desktop/lruler-blog/be/node_modules/koa-static-cache/index.js:39:63
    at async notfound (/Users/lruler/Desktop/lruler-blog/be/node_modules/egg/app/middleware/notfound.js:5:5)
code: "P2002"
clientVersion: "3.10.0"
meta: {"target":"Tags_tag_key"}
name: "P2002Error"
pid: 54794
hostname: liuyuledeMacBook-Pro.local

2022-02-27 11:20:36,853 ERROR 57395 [-/127.0.0.1/-/101ms POST /blog/add] nodejs.P2002Error: 
Invalid `prisma.tags.create()` invocation in
/Users/lruler/Desktop/lruler-blog/be/app/controller/blog.ts:27:30

  24 await Promise.all(blogTags.map(async t => {
  25   const o = await prisma.tags.findUnique({ where: { tag: t.tag } });
  26   if (o) await prisma.tags.update({ where: { tag: o.tag }, data: { count: ++o.count } });
→ 27   else await prisma.tags.create(
  Unique constraint failed on the constraint: `Tags_tag_key`
Invalid `prisma.tags.create()` invocation in
/Users/lruler/Desktop/lruler-blog/be/app/controller/blog.ts:27:30

  24 await Promise.all(blogTags.map(async t => {
  25   const o = await prisma.tags.findUnique({ where: { tag: t.tag } });
  26   if (o) await prisma.tags.update({ where: { tag: o.tag }, data: { count: ++o.count } });
→ 27   else await prisma.tags.create(
  Unique constraint failed on the constraint: `Tags_tag_key`
    at Object.request (/Users/lruler/Desktop/lruler-blog/be/node_modules/@prisma/client/runtime/index.js:39809:15)
    at async PrismaClient._request (/Users/lruler/Desktop/lruler-blog/be/node_modules/@prisma/client/runtime/index.js:40637:18)
    at async /Users/lruler/Desktop/lruler-blog/be/app/controller/blog.ts:27:12
    at async Promise.all (index 0)
    at async BlogController.addBlog (/Users/lruler/Desktop/lruler-blog/be/app/controller/blog.ts:24:5)
    at async /Users/lruler/Desktop/lruler-blog/be/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async session (/Users/lruler/Desktop/lruler-blog/be/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/Users/lruler/Desktop/lruler-blog/be/node_modules/koa-bodyparser/index.js:95:5)
    at async /Users/lruler/Desktop/lruler-blog/be/node_modules/koa-static-cache/index.js:39:63
    at async notfound (/Users/lruler/Desktop/lruler-blog/be/node_modules/egg/app/middleware/notfound.js:5:5)
code: "P2002"
clientVersion: "3.10.0"
meta: {"target":"Tags_tag_key"}
name: "P2002Error"
pid: 57395
hostname: liuyuledeMacBook-Pro.local

2022-02-27 11:21:47,205 ERROR 57395 [-/127.0.0.1/-/86ms POST /blog/add] nodejs.P2002Error: 
Invalid `prisma.tags.create()` invocation in
/Users/lruler/Desktop/lruler-blog/be/app/controller/blog.ts:27:30

  24 await Promise.all(blogTags.map(async t => {
  25   const o = await prisma.tags.findUnique({ where: { tag: t.tag } });
  26   if (o) await prisma.tags.update({ where: { tag: o.tag }, data: { count: ++o.count } });
→ 27   else await prisma.tags.create(
  Unique constraint failed on the constraint: `Tags_tag_key`
Invalid `prisma.tags.create()` invocation in
/Users/lruler/Desktop/lruler-blog/be/app/controller/blog.ts:27:30

  24 await Promise.all(blogTags.map(async t => {
  25   const o = await prisma.tags.findUnique({ where: { tag: t.tag } });
  26   if (o) await prisma.tags.update({ where: { tag: o.tag }, data: { count: ++o.count } });
→ 27   else await prisma.tags.create(
  Unique constraint failed on the constraint: `Tags_tag_key`
    at Object.request (/Users/lruler/Desktop/lruler-blog/be/node_modules/@prisma/client/runtime/index.js:39809:15)
    at async PrismaClient._request (/Users/lruler/Desktop/lruler-blog/be/node_modules/@prisma/client/runtime/index.js:40637:18)
    at async /Users/lruler/Desktop/lruler-blog/be/app/controller/blog.ts:27:12
    at async Promise.all (index 0)
    at async BlogController.addBlog (/Users/lruler/Desktop/lruler-blog/be/app/controller/blog.ts:24:5)
    at async /Users/lruler/Desktop/lruler-blog/be/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async session (/Users/lruler/Desktop/lruler-blog/be/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/Users/lruler/Desktop/lruler-blog/be/node_modules/koa-bodyparser/index.js:95:5)
    at async /Users/lruler/Desktop/lruler-blog/be/node_modules/koa-static-cache/index.js:39:63
    at async notfound (/Users/lruler/Desktop/lruler-blog/be/node_modules/egg/app/middleware/notfound.js:5:5)
code: "P2002"
clientVersion: "3.10.0"
meta: {"target":"Tags_tag_key"}
name: "P2002Error"
pid: 57395
hostname: liuyuledeMacBook-Pro.local

2022-02-27 11:24:18,070 ERROR 57593 [-/127.0.0.1/-/116ms POST /blog/add] nodejs.P2002Error: 
Invalid `prisma.tags.create()` invocation in
/Users/lruler/Desktop/lruler-blog/be/app/controller/blog.ts:28:30

  25 await Promise.all(blogTags.map(async t => {
  26   const o = await prisma.tags.findUnique({ where: { tag: t.tag } });
  27   if (o) await prisma.tags.update({ where: { tag: o.tag }, data: { count: ++o.count } });
→ 28   else await prisma.tags.create(
  Unique constraint failed on the constraint: `Tags_tag_key`
Invalid `prisma.tags.create()` invocation in
/Users/lruler/Desktop/lruler-blog/be/app/controller/blog.ts:28:30

  25 await Promise.all(blogTags.map(async t => {
  26   const o = await prisma.tags.findUnique({ where: { tag: t.tag } });
  27   if (o) await prisma.tags.update({ where: { tag: o.tag }, data: { count: ++o.count } });
→ 28   else await prisma.tags.create(
  Unique constraint failed on the constraint: `Tags_tag_key`
    at Object.request (/Users/lruler/Desktop/lruler-blog/be/node_modules/@prisma/client/runtime/index.js:39809:15)
    at async PrismaClient._request (/Users/lruler/Desktop/lruler-blog/be/node_modules/@prisma/client/runtime/index.js:40637:18)
    at async /Users/lruler/Desktop/lruler-blog/be/app/controller/blog.ts:28:12
    at async Promise.all (index 0)
    at async BlogController.addBlog (/Users/lruler/Desktop/lruler-blog/be/app/controller/blog.ts:25:5)
    at async /Users/lruler/Desktop/lruler-blog/be/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async session (/Users/lruler/Desktop/lruler-blog/be/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/Users/lruler/Desktop/lruler-blog/be/node_modules/koa-bodyparser/index.js:95:5)
    at async /Users/lruler/Desktop/lruler-blog/be/node_modules/koa-static-cache/index.js:39:63
    at async notfound (/Users/lruler/Desktop/lruler-blog/be/node_modules/egg/app/middleware/notfound.js:5:5)
code: "P2002"
clientVersion: "3.10.0"
meta: {"target":"Tags_tag_key"}
name: "P2002Error"
pid: 57593
hostname: liuyuledeMacBook-Pro.local

2022-02-27 11:26:07,660 ERROR 57700 [-/127.0.0.1/-/64ms POST /blog/add] nodejs.P2002Error: 
Invalid `prisma.tags.create()` invocation in
/Users/lruler/Desktop/lruler-blog/be/app/controller/blog.ts:28:30

  25 console.log(t);
  26 const o = await prisma.tags.findUnique({ where: { tag: t.tag } });
  27 if (o) await prisma.tags.update({ where: { tag: o.tag }, data: { count: ++o.count } });
→ 28 else await prisma.tags.create(
  Unique constraint failed on the constraint: `Tags_tag_key`
Invalid `prisma.tags.create()` invocation in
/Users/lruler/Desktop/lruler-blog/be/app/controller/blog.ts:28:30

  25 console.log(t);
  26 const o = await prisma.tags.findUnique({ where: { tag: t.tag } });
  27 if (o) await prisma.tags.update({ where: { tag: o.tag }, data: { count: ++o.count } });
→ 28 else await prisma.tags.create(
  Unique constraint failed on the constraint: `Tags_tag_key`
    at Object.request (/Users/lruler/Desktop/lruler-blog/be/node_modules/@prisma/client/runtime/index.js:39809:15)
    at async PrismaClient._request (/Users/lruler/Desktop/lruler-blog/be/node_modules/@prisma/client/runtime/index.js:40637:18)
    at async /Users/lruler/Desktop/lruler-blog/be/app/controller/blog.ts:28:12
    at async Promise.all (index 0)
    at async BlogController.addBlog (/Users/lruler/Desktop/lruler-blog/be/app/controller/blog.ts:24:5)
    at async /Users/lruler/Desktop/lruler-blog/be/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async session (/Users/lruler/Desktop/lruler-blog/be/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/Users/lruler/Desktop/lruler-blog/be/node_modules/koa-bodyparser/index.js:95:5)
    at async /Users/lruler/Desktop/lruler-blog/be/node_modules/koa-static-cache/index.js:39:63
    at async notfound (/Users/lruler/Desktop/lruler-blog/be/node_modules/egg/app/middleware/notfound.js:5:5)
code: "P2002"
clientVersion: "3.10.0"
meta: {"target":"Tags_tag_key"}
name: "P2002Error"
pid: 57700
hostname: liuyuledeMacBook-Pro.local

2022-02-27 11:28:34,944 ERROR 57932 [-/127.0.0.1/-/66ms POST /blog/add] nodejs.P2002Error: 
Invalid `prisma.tags.create()` invocation in
/Users/lruler/Desktop/lruler-blog/be/app/controller/blog.ts:28:30

  25 console.log(t);
  26 const o = await prisma.tags.findUnique({ where: { tag: t.tag } });
  27 if (o) await prisma.tags.update({ where: { tag: o.tag }, data: { count: ++o.count } });
→ 28 else await prisma.tags.create(
  Unique constraint failed on the constraint: `Tags_tag_key`
Invalid `prisma.tags.create()` invocation in
/Users/lruler/Desktop/lruler-blog/be/app/controller/blog.ts:28:30

  25 console.log(t);
  26 const o = await prisma.tags.findUnique({ where: { tag: t.tag } });
  27 if (o) await prisma.tags.update({ where: { tag: o.tag }, data: { count: ++o.count } });
→ 28 else await prisma.tags.create(
  Unique constraint failed on the constraint: `Tags_tag_key`
    at Object.request (/Users/lruler/Desktop/lruler-blog/be/node_modules/@prisma/client/runtime/index.js:39809:15)
    at async PrismaClient._request (/Users/lruler/Desktop/lruler-blog/be/node_modules/@prisma/client/runtime/index.js:40637:18)
    at async /Users/lruler/Desktop/lruler-blog/be/app/controller/blog.ts:28:12
    at async Promise.all (index 0)
    at async BlogController.addBlog (/Users/lruler/Desktop/lruler-blog/be/app/controller/blog.ts:24:5)
    at async /Users/lruler/Desktop/lruler-blog/be/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async session (/Users/lruler/Desktop/lruler-blog/be/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/Users/lruler/Desktop/lruler-blog/be/node_modules/koa-bodyparser/index.js:95:5)
    at async /Users/lruler/Desktop/lruler-blog/be/node_modules/koa-static-cache/index.js:39:63
    at async notfound (/Users/lruler/Desktop/lruler-blog/be/node_modules/egg/app/middleware/notfound.js:5:5)
code: "P2002"
clientVersion: "3.10.0"
meta: {"target":"Tags_tag_key"}
name: "P2002Error"
pid: 57932
hostname: liuyuledeMacBook-Pro.local

2022-02-27 11:53:53,980 ERROR 58515 [-/127.0.0.1/-/47ms POST /blog/upload] nodejs.TypeError: the multipart request can't be consumed twice
    at Object.multipart (/Users/lruler/Desktop/lruler-blog/be/node_modules/egg-multipart/app/extend/context.js:181:35)
    at Object.getFileStream (/Users/lruler/Desktop/lruler-blog/be/node_modules/egg-multipart/app/extend/context.js:227:24)
    at BlogController.uploadImg (/Users/lruler/Desktop/lruler-blog/be/app/controller/blog.ts:63:30)
    at Object.callFn (/Users/lruler/Desktop/lruler-blog/be/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/lruler/Desktop/lruler-blog/be/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/lruler/Desktop/lruler-blog/be/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/lruler/Desktop/lruler-blog/be/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/lruler/Desktop/lruler-blog/be/node_modules/@eggjs/router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/lruler/Desktop/lruler-blog/be/node_modules/@eggjs/router/node_modules/koa-compose/index.js:45:18)
    at /Users/lruler/Desktop/lruler-blog/be/node_modules/@eggjs/router/lib/router.js:186:18

pid: 58515
hostname: liuyuledeMacBook-Pro.local

2022-02-27 11:54:39,571 ERROR 58515 [-/127.0.0.1/-/20ms POST /blog/upload] nodejs.TypeError: the multipart request can't be consumed twice
    at Object.multipart (/Users/lruler/Desktop/lruler-blog/be/node_modules/egg-multipart/app/extend/context.js:181:35)
    at Object.getFileStream (/Users/lruler/Desktop/lruler-blog/be/node_modules/egg-multipart/app/extend/context.js:227:24)
    at BlogController.uploadImg (/Users/lruler/Desktop/lruler-blog/be/app/controller/blog.ts:63:30)
    at Object.callFn (/Users/lruler/Desktop/lruler-blog/be/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/lruler/Desktop/lruler-blog/be/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/lruler/Desktop/lruler-blog/be/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/lruler/Desktop/lruler-blog/be/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/lruler/Desktop/lruler-blog/be/node_modules/@eggjs/router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/lruler/Desktop/lruler-blog/be/node_modules/@eggjs/router/node_modules/koa-compose/index.js:45:18)
    at /Users/lruler/Desktop/lruler-blog/be/node_modules/@eggjs/router/lib/router.js:186:18

pid: 58515
hostname: liuyuledeMacBook-Pro.local

2022-02-27 11:55:24,284 ERROR 58515 [-/127.0.0.1/-/20ms POST /blog/upload] nodejs.TypeError: the multipart request can't be consumed twice
    at Object.multipart (/Users/lruler/Desktop/lruler-blog/be/node_modules/egg-multipart/app/extend/context.js:181:35)
    at Object.getFileStream (/Users/lruler/Desktop/lruler-blog/be/node_modules/egg-multipart/app/extend/context.js:227:24)
    at BlogController.uploadImg (/Users/lruler/Desktop/lruler-blog/be/app/controller/blog.ts:63:30)
    at Object.callFn (/Users/lruler/Desktop/lruler-blog/be/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/lruler/Desktop/lruler-blog/be/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/lruler/Desktop/lruler-blog/be/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/lruler/Desktop/lruler-blog/be/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/lruler/Desktop/lruler-blog/be/node_modules/@eggjs/router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/lruler/Desktop/lruler-blog/be/node_modules/@eggjs/router/node_modules/koa-compose/index.js:45:18)
    at /Users/lruler/Desktop/lruler-blog/be/node_modules/@eggjs/router/lib/router.js:186:18

pid: 58515
hostname: liuyuledeMacBook-Pro.local

2022-02-27 12:38:59,692 ERROR 57393 nodejs.ClusterClientNoResponseError: client no response in 953478ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 57393
hostname: liuyuledeMacBook-Pro.local

2022-02-27 13:11:23,727 ERROR 57393 nodejs.ClusterClientNoResponseError: client no response in 911689ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 57393
hostname: liuyuledeMacBook-Pro.local

2022-02-27 13:28:53,561 ERROR 57393 nodejs.ClusterClientNoResponseError: client no response in 1049710ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 57393
hostname: liuyuledeMacBook-Pro.local

2022-02-27 14:01:20,534 ERROR 57393 nodejs.ClusterClientNoResponseError: client no response in 1025675ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 57393
hostname: liuyuledeMacBook-Pro.local

2022-02-27 14:19:15,442 ERROR 57393 nodejs.ClusterClientNoResponseError: client no response in 1074902ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 57393
hostname: liuyuledeMacBook-Pro.local

2022-02-27 14:35:10,249 ERROR 57393 nodejs.ClusterClientNoResponseError: client no response in 954802ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 57393
hostname: liuyuledeMacBook-Pro.local

2022-02-27 14:52:14,979 ERROR 57393 nodejs.ClusterClientNoResponseError: client no response in 1024724ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 57393
hostname: liuyuledeMacBook-Pro.local

2022-02-27 15:07:26,709 ERROR 57393 nodejs.ClusterClientNoResponseError: client no response in 911726ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 57393
hostname: liuyuledeMacBook-Pro.local

2022-02-27 15:23:01,654 ERROR 57393 nodejs.ClusterClientNoResponseError: client no response in 934815ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 57393
hostname: liuyuledeMacBook-Pro.local

2022-02-27 15:40:59,229 ERROR 57393 nodejs.ClusterClientNoResponseError: client no response in 1077569ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 57393
hostname: liuyuledeMacBook-Pro.local

2022-02-27 15:57:24,923 ERROR 57393 nodejs.ClusterClientNoResponseError: client no response in 985675ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 57393
hostname: liuyuledeMacBook-Pro.local

2022-02-27 17:31:45,703 ERROR 57393 nodejs.ClusterClientNoResponseError: client no response in 935444ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 57393
hostname: liuyuledeMacBook-Pro.local

2022-02-27 18:05:25,285 ERROR 57393 nodejs.ClusterClientNoResponseError: client no response in 981700ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 57393
hostname: liuyuledeMacBook-Pro.local

2022-02-27 18:20:57,975 ERROR 57393 nodejs.ClusterClientNoResponseError: client no response in 932687ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 57393
hostname: liuyuledeMacBook-Pro.local

2022-02-27 18:30:34,756 ERROR 57393 nodejs.ClusterClientNoResponseError: client no response in 576771ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 57393
hostname: liuyuledeMacBook-Pro.local

2022-02-27 19:02:11,653 ERROR 57393 nodejs.ClusterClientNoResponseError: client no response in 1076756ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lruler/Desktop/lruler-blog/be/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 57393
hostname: liuyuledeMacBook-Pro.local

